// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: general/paginate.proto

package general

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PaginateQuery struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gotags: log_field:"paginate.page"
	Page int64 `protobuf:"varint,1,opt,name=Page,proto3" json:"Page,omitempty" log_field:"paginate.page"` // 页码
	// @gotags: log_field:"paginate.page_size"
	PageSize int64 `protobuf:"varint,2,opt,name=PageSize,proto3" json:"PageSize,omitempty" log_field:"paginate.page_size"` // 每页大小
}

func (x *PaginateQuery) Reset() {
	*x = PaginateQuery{}
	if protoimpl.UnsafeEnabled {
		mi := &file_general_paginate_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PaginateQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginateQuery) ProtoMessage() {}

func (x *PaginateQuery) ProtoReflect() protoreflect.Message {
	mi := &file_general_paginate_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginateQuery.ProtoReflect.Descriptor instead.
func (*PaginateQuery) Descriptor() ([]byte, []int) {
	return file_general_paginate_proto_rawDescGZIP(), []int{0}
}

func (x *PaginateQuery) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PaginateQuery) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type PaginateInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gotags: json:"page"
	Page int64 `protobuf:"varint,1,opt,name=Page,proto3" json:"page"` // 页码
	// @gotags: json:"page_size"
	PageSize int64 `protobuf:"varint,2,opt,name=PageSize,proto3" json:"page_size"` // 每页大小
	// @gotags: json:"total"
	Total int64 `protobuf:"varint,3,opt,name=Total,proto3" json:"total"` // 数据总数
}

func (x *PaginateInfo) Reset() {
	*x = PaginateInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_general_paginate_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PaginateInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginateInfo) ProtoMessage() {}

func (x *PaginateInfo) ProtoReflect() protoreflect.Message {
	mi := &file_general_paginate_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginateInfo.ProtoReflect.Descriptor instead.
func (*PaginateInfo) Descriptor() ([]byte, []int) {
	return file_general_paginate_proto_rawDescGZIP(), []int{1}
}

func (x *PaginateInfo) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PaginateInfo) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *PaginateInfo) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_general_paginate_proto protoreflect.FileDescriptor

var file_general_paginate_proto_rawDesc = []byte{
	0x0a, 0x16, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x6c, 0x2f, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61,
	0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61,
	0x6c, 0x22, 0x3f, 0x0a, 0x0d, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x51, 0x75, 0x65,
	0x72, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x50, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x04, 0x50, 0x61, 0x67, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x61, 0x67, 0x65, 0x53, 0x69,
	0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x50, 0x61, 0x67, 0x65, 0x53, 0x69,
	0x7a, 0x65, 0x22, 0x54, 0x0a, 0x0c, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x50, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x04, 0x50, 0x61, 0x67, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x61, 0x67, 0x65, 0x53, 0x69,
	0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x50, 0x61, 0x67, 0x65, 0x53, 0x69,
	0x7a, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x05, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x42, 0x27, 0x5a, 0x25, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x59, 0x6f, 0x73, 0x74, 0x61, 0x72, 0x64, 0x65, 0x76,
	0x2f, 0x63, 0x6d, 0x64, 0x62, 0x2d, 0x73, 0x64, 0x6b, 0x2f, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61,
	0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_general_paginate_proto_rawDescOnce sync.Once
	file_general_paginate_proto_rawDescData = file_general_paginate_proto_rawDesc
)

func file_general_paginate_proto_rawDescGZIP() []byte {
	file_general_paginate_proto_rawDescOnce.Do(func() {
		file_general_paginate_proto_rawDescData = protoimpl.X.CompressGZIP(file_general_paginate_proto_rawDescData)
	})
	return file_general_paginate_proto_rawDescData
}

var file_general_paginate_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_general_paginate_proto_goTypes = []interface{}{
	(*PaginateQuery)(nil), // 0: general.PaginateQuery
	(*PaginateInfo)(nil),  // 1: general.PaginateInfo
}
var file_general_paginate_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_general_paginate_proto_init() }
func file_general_paginate_proto_init() {
	if File_general_paginate_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_general_paginate_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PaginateQuery); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_general_paginate_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PaginateInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_general_paginate_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_general_paginate_proto_goTypes,
		DependencyIndexes: file_general_paginate_proto_depIdxs,
		MessageInfos:      file_general_paginate_proto_msgTypes,
	}.Build()
	File_general_paginate_proto = out.File
	file_general_paginate_proto_rawDesc = nil
	file_general_paginate_proto_goTypes = nil
	file_general_paginate_proto_depIdxs = nil
}
